output-format: grouped
strictness: veryhigh
test-warnings: true
max-line-length: 120
pylint:
    disable:
      - import-error
      - invalid-name
      - redefined-outer-name
      - too-few-public-methods
      - expression-not-assigned
      - too-many-instance-attributes
